services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: primus-app
    volumes:
      - ./:/app
    environment:
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=primus
      COMPOSER_MEMORY_LIMIT: -1
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: fish
